version: '3.8'

services:
  # Production deployment from Docker Hub
  ovenplayer-prod:
    image: npdang9472/ovenplayer:latest
    ports:
      - "80:80"
    container_name: ovenplayer-production
    restart: unless-stopped
    profiles:
      - production

  # Development build with hot reloading
  ovenplayer-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "8081:8080"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: ovenplayer-development
    environment:
      - NODE_ENV=development
    profiles:
      - development

  # Static file server for development testing
  ovenplayer-static:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./dist:/usr/share/nginx/html/dist
      - ./demo:/usr/share/nginx/html/demo
      - ./src/assets:/usr/share/nginx/html/src/assets
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: ovenplayer-static
    depends_on:
      - ovenplayer-dev
    profiles:
      - development

networks:
  default:
    name: ovenplayer-network